url: http://www.rembrandt.builders
baseurl: rembrandt.builders

# Site settings
title: Rembrandt Builders
email: yooll@me.com
description: "For three decades, Rembrandt Builders has been building custom luxury homes in the Washington, D.C. Metropolitan Area. We love to make happy clients by providing and satisying all their needs and dreams."


# Team names, titles and social links
people:
- name: Jim
  pic: 1
  position: Head Home Builder
  alt: Jim, CEO and founder of Rembrandt Builders
  

- name: Christina
  pic: 2
  position: Interior'issima
  alt: Christina, Interior Designer For Rembrandt Builders
  

- name: Keith
  pic: 3
  position: Master Artisan
  alt: Keith, master artisan and carpenter for Rembrandt Builders
  

- name: David
  pic: 4
  position: Big Dig Operator
  alt: David, equipment operator for Rembrandt Builders

  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/RembrandtBuilders/
  - title: houzz
    url: http://www.houzz.es/pro/rembrandt-builders/rembrandt-builderscom?irs=US
  - title: google-plus
    url: https://plus.google.com/+RembrandtBuildersBethesda

# Postal address (add as many lines as necessary)
address:
  - line: 5825 Rolling Dr.
  - line: Derwood, MD 20855

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
include: ['.well-known']