url: https://y7kim.github.io
baseurl: /home/

# Site settings
title: Rembrandt Builders, Inc.
email: yooll@me.com
description: "For three decades, Rembrandt Builders, Inc. has been building custom homes in the Washington, D.C. Metropolitan Area."


# Team names, titles and social links
people:
- name: Jim
  pic: 1
  position: Head Home Builder
  

- name: Christina
  pic: 2
  position: Interior'issima
  

- name: Keith
  pic: 3
  position: Master Artisan
  

- name: David
  pic: 4
  position: Big Dig Operator

  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/RembrandtBuilders/
  - title: houzz
    url: http://www.houzz.es/pro/rembrandt-builders/rembrandt-builderscom?irs=US
  - title: google-plus
    url: https://plus.google.com/+RembrandtBuildersBethesda

# Postal address (add as many lines as necessary)
address:
  - line: 5825 Rolling Dr.
  - line: Derwood, MD 20855

# Build settings
markdown: kramdown
permalink: pretty